import binascii

#the values that Eve intercepted 
g = 7
p = 61
A = 30
B = 17

#find the random a that Alice generated by testing a bunch 
#of possible values until it solves 
for i in range(100):
    if (((g^i)%p) == A):
        print(str(i) + " is a!")
        a = i
        break

#solve for K !!! 
K = (B^a)%p 
print(str(K) + " is K!")

#solve for d 
e = 17
p = 379
q = 449
for d in range(100000000):
    if ((e*d)%((p-1)*(q-1)) == 1):
        print(str(d) + " is d!")
        break

encrypted = [65426, 79042, 53889, 42039, 49636, 66493, 41225, 58964,
126715, 67136, 146654, 30668, 159166, 75253, 123703, 138090,
118085, 120912, 117757, 145306, 10450, 135932, 152073, 141695,
42039, 137851, 44057, 16497, 100682, 12397, 92727, 127363,
146760, 5303, 98195, 26070, 110936, 115638, 105827, 152109,
79912, 74036, 26139, 64501, 71977, 128923, 106333, 126715,
111017, 165562, 157545, 149327, 60143, 117253, 21997, 135322,
19408, 36348, 103851, 139973, 35671, 93761, 11423, 41336,
36348, 41336, 156366, 140818, 156366, 93166, 128570, 19681,
26139, 39292, 114290, 19681, 149668, 70117, 163780, 73933,
154421, 156366, 126548, 87726, 41418, 87726, 3486, 151413,
26421, 99611, 157545, 101582, 100345, 60758, 92790, 13012,
100704, 107995]

#decode the message 
d = 119537
n = 170171
decoded = ""
for cipher in encrypted: 
    binary = str(bin((cipher**d)%n))
    binary = binary[2:10]
    while(len(binary) < 18):
        binary = "0" + binary
    binary1 = binary[2:10]
    binary2 = binary[10:]
    decoded += binary1 + " " + binary2 + " "
print(decoded)
